-- Demo users are seeded with bcrypt hashes for the password Demo@123.
-- Hashes are generated by bcrypt (12 rounds); plaintext passwords are never inserted.
USE pharmsync;

INSERT INTO users
  (full_name, email, phone, password_hash, role, organization_name, license_number, registration_number, address, city, state, verified, active)
VALUES
  ('Ramesh Kumar', 'ramesh@pharmsync.demo', '9000000001', '$2b$12$353XlinZt72KCLRMkGRHOOZo4taUmSwgAp0d8PpvbJAMrCE67GGhK', 'retail_chemist', 'Ramesh Medicals', 'KA-MED-1001', NULL, 'MG Road', 'Bengaluru', 'Karnataka', TRUE, TRUE),
  ('Dr. Priya', 'priya@pharmsync.demo', '9000000002', '$2b$12$353XlinZt72KCLRMkGRHOOZo4taUmSwgAp0d8PpvbJAMrCE67GGhK', 'clinic_phc', 'Priya Community Clinic', NULL, 'CLINIC-KA-001', 'Indiranagar', 'Bengaluru', 'Karnataka', TRUE, TRUE),
  ('Helping Hands Coordinator', 'charity@pharmsync.demo', '9000000003', '$2b$12$353XlinZt72KCLRMkGRHOOZo4taUmSwgAp0d8PpvbJAMrCE67GGhK', 'charity_ngo', 'Helping Hands Free Clinic', NULL, 'NGO-KA-001', 'Jayanagar', 'Bengaluru', 'Karnataka', TRUE, TRUE)
ON DUPLICATE KEY UPDATE
  full_name = VALUES(full_name), phone = VALUES(phone), password_hash = VALUES(password_hash),
  role = VALUES(role), organization_name = VALUES(organization_name),
  license_number = VALUES(license_number), registration_number = VALUES(registration_number),
  verified = VALUES(verified), active = VALUES(active);