import { useCallback, useEffect, useState } from 'react'
import { ArrowRight, CheckCircle2, CircleAlert, MapPin, PackageSearch, RefreshCw, Search, ShieldCheck, ShoppingBag } from 'lucide-react'
import { Link } from 'react-router-dom'
import Navbar from '../components/Navbar'
import api from '../services/api'

const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2}).format(Number(v||0))
const productKey=o=>`${o.medicine_id}|${String(o.medicine_name||'').toLocaleLowerCase().replace(/\s+/g,' ').trim()}`
export default function PatientMarketplace(){
 const [search,setSearch]=useState('');const [nodeId,setNodeId]=useState('');const [offers,setOffers]=useState([]);const [pharmacies,setPharmacies]=useState([]);const [quantities,setQuantities]=useState({});const [maxOrderQuantity,setMaxOrderQuantity]=useState(2);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState('')
 const load=useCallback(async(query=search)=>{setLoading(true);setError('');try{const [result,stores]=await Promise.all([api.get('/medicines',{params:{search:query}}),api.get('/medicines/pharmacies')]);setOffers(result.data.offers||[]);setMaxOrderQuantity(Number(result.data.maximum_request_quantity||2));setPharmacies(stores.data.pharmacies||[])}catch(e){setError(e.userMessage||'Unable to check live PharmSync availability.')}finally{setLoading(false)}},[search])
 useEffect(()=>{const timer=setTimeout(()=>load(search),250);return()=>clearTimeout(timer)},[search,load])
 const atSelected=offers.filter(o=>!nodeId||o.node_id===nodeId)
 const selectedProducts=new Set(atSelected.map(productKey))
 const alternatives=offers.filter(o=>nodeId&&search.trim()&&o.node_id!==nodeId&&!selectedProducts.has(productKey(o)))
 const request=async offer=>{const quantity=Number(quantities[offer.batch_id]||1);setBusy(offer.batch_id);setError('');setNotice('');try{const {data}=await api.post('/orders',{batch_id:offer.batch_id,quantity});setNotice(`${data.message} ${offer.medicine_name} · ${quantity} strip${quantity===1?'':'s'} · ${money(data.order.total_amount)}.`);await load(search)}catch(e){setError(e.response?.data?.detail||e.userMessage||'Unable to submit your medicine request.')}finally{setBusy('')}}
 const card=offer=><article className="market-card" key={offer.batch_id}><div className="market-card-top"><span className="market-icon"><PackageSearch size={18}/></span><span className="market-discount">{offer.discount_percent}% OFF</span></div><h2>{offer.medicine_name}</h2><div className="market-product-sub">{offer.medicine_id}{offer.form?` · ${offer.form}`:''} · Batch {offer.batch_id}</div><div className="market-price"><b>{money(offer.offer_price)}</b><del>{money(offer.original_price)}</del><small>/ strip</small></div><div className="market-facts"><span><b>{offer.available_quantity}</b> available</span><span><b>{offer.days_remaining}</b> days to expiry</span><span>Expires <b>{new Date(`${String(offer.expiry_date).slice(0,10)}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</b></span></div><div className="market-pharmacy"><MapPin size={14}/><span><b>{offer.pharmacy_name}</b><small>{[offer.city,offer.state].filter(Boolean).join(', ')||'Location not provided'}</small></span></div><div className="market-order-control"><label>Quantity<select value={quantities[offer.batch_id]||1} onChange={e=>setQuantities(old=>({...old,[offer.batch_id]:Number(e.target.value)}))}>{Array.from({length:offer.maximum_request_quantity},(_,i)=><option key={i+1} value={i+1}>{i+1} strip{i?'s':''}</option>)}</select></label><span>Limit {offer.maximum_request_quantity} per order</span></div><button className="button button-green market-request" disabled={busy===offer.batch_id} onClick={()=>request(offer)}>{busy===offer.batch_id?'Sending request…':'Request medicine'} <ArrowRight size={15}/></button></article>
 return <div className="site-shell module-shell"><Navbar/><main className="module-page wrap patient-page"><div className="module-heading"><div><span className="eyebrow">CONNECTED PHARMACY NETWORK</span><h1>Find discounted medicine</h1><p>Browse current, verified pharmacy offers. Availability and prices are checked from MySQL before each request.</p></div><Link className="button button-quiet" to="/my-orders"><ShoppingBag size={15}/> My orders</Link></div>
   {error&&<div className="module-error" role="alert"><CircleAlert size={15}/>{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="module-notice" role="status"><CheckCircle2 size={15}/><span>{notice}</span><Link to="/my-orders">View orders</Link><button onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}
   <section className="market-search-panel"><label className="market-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search medicine name, ID or form…"/><kbd>SEARCH LIVE STOCK</kbd></label><label className="market-pharmacy-filter"><span>Check at pharmacy</span><select value={nodeId} onChange={e=>setNodeId(e.target.value)}><option value="">All connected pharmacies</option>{pharmacies.map(p=><option key={p.node_id} value={p.node_id}>{p.node_name} · {[p.city,p.state].filter(Boolean).join(', ')}</option>)}</select></label><div className="market-safety-note"><ShieldCheck size={14}/> Only verified pharmacies and eligible 30% / 50% discount batches are shown. Requests are limited to {maxOrderQuantity} strip{maxOrderQuantity===1?'':'s'} per medicine.</div></section>
   <div className="market-section-head"><div><span className="tiny-label">LIVE MYSQL AVAILABILITY</span><h2>{search.trim()?'Search results':'Eligible offers'} <span>{loading?'…':atSelected.length}</span></h2></div><button className="button button-quiet" onClick={()=>load(search)} disabled={loading}><RefreshCw size={14} className={loading?'spinner-icon':''}/> Refresh</button></div>
   {loading?<div className="market-empty">Checking current pharmacy inventory…</div>:atSelected.length?<div className="market-grid">{atSelected.map(card)}</div>:nodeId&&alternatives.length?<section className="market-alternative"><div className="market-alternative-title"><div><span className="tiny-label">ALTERNATIVE PHARMACY SUGGESTIONS</span><h2>Medicine available from another connected pharmacy</h2><p>There are no eligible offers at the selected pharmacy. These alternatives have live stock in MySQL.</p></div><span className="transfer-live"><i/> Verified stock</span></div><div className="market-grid">{alternatives.map(card)}</div></section>:<div className="market-empty"><PackageSearch size={23}/><b>{search.trim()?'Medicine currently unavailable':'No eligible discounted medicines right now'}</b><span>{search.trim()?'This medicine is currently unavailable in the connected PharmSync network.':'Offers appear when verified pharmacies have eligible expiry-risk batches with available stock.'}</span></div>}
   {nodeId&&atSelected.length>0&&alternatives.length>0&&<section className="market-more-alternatives"><h2>Also available at other pharmacies</h2><div className="market-grid">{alternatives.map(card)}</div></section>}
   <div className="module-disclaimer"><ShieldCheck size={14}/> A request reserves the chosen quantity. The pharmacy must confirm it; cancellation releases the reservation. Collect medicine only through the pharmacy’s instructions.</div>
 </main></div>
}
