import { useCallback, useEffect, useState } from 'react'
import { Bell, Check, CircleAlert, Clock3, PackageCheck, RefreshCw, ShieldCheck, X } from 'lucide-react'
import Navbar from '../components/Navbar'
import api from '../services/api'

const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v||0))
const key=v=>String(v||'').toUpperCase().replaceAll(' ','_')
const groups=[['PENDING','New requests'],['CONFIRMED','Confirmed'],['READY_FOR_PICKUP','Ready for pickup'],['COMPLETED','Completed'],['CANCELLED','Cancelled']]
export default function PharmacyOrders(){
 const [orders,setOrders]=useState([]);const [pendingCount,setPendingCount]=useState(0);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('')
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const {data}=await api.get('/pharmacy/orders');setOrders(data.orders||[]);setPendingCount(Number(data.pending_count||0));setError('')}catch(e){setError(e.userMessage||'Unable to load pharmacy medicine requests.')}finally{if(!silent)setLoading(false)}},[])
 useEffect(()=>{load();const id=setInterval(()=>load(true),20000);return()=>clearInterval(id)},[load])
 const update=async(order,status)=>{setBusy(order.order_id);setError('');setNotice('');try{await api.patch(`/pharmacy/orders/${order.order_id}/status`,{status});setNotice(`Order ${order.order_id} updated to ${status.replaceAll('_',' ')}.`);await load()}catch(e){setError(e.response?.data?.detail||e.userMessage||'Unable to update the order.')}finally{setBusy('')}}
 const actions=order=>{const s=key(order.status);return <div className="order-actions">{s==='PENDING'&&<><button className="button button-green" disabled={busy===order.order_id} onClick={()=>update(order,'CONFIRMED')}><Check size={13}/> Confirm</button><button className="button button-quiet" disabled={busy===order.order_id} onClick={()=>update(order,'CANCELLED')}><X size={13}/> Cancel</button></>}{s==='CONFIRMED'&&<><button className="button button-green" disabled={busy===order.order_id} onClick={()=>update(order,'READY_FOR_PICKUP')}><PackageCheck size={13}/> Ready for pickup</button><button className="button button-quiet" disabled={busy===order.order_id} onClick={()=>update(order,'CANCELLED')}><X size={13}/> Cancel</button></>}{s==='READY_FOR_PICKUP'&&<button className="button button-green" disabled={busy===order.order_id} onClick={()=>update(order,'COMPLETED')}><Check size={13}/> Complete pickup</button>}</div>}
 return <div className="site-shell module-shell"><Navbar/><main className="module-page wrap patient-page pharmacy-orders-page"><div className="module-heading"><div><span className="eyebrow">PHARMACY OPERATIONS · LIVE MYSQL ORDERS</span><h1>Medicine requests</h1><p>Requests are scoped to your authenticated pharmacy node. Changes sync to each patient’s My Orders view.</p></div><button className="button button-quiet" onClick={()=>load()} disabled={loading}><RefreshCw size={14} className={loading?'spinner-icon':''}/> Refresh</button></div>
   {pendingCount>0&&<div className="new-order-notice"><span><Bell size={17}/></span><div><b>New medicine request{pendingCount===1?'':'s'}</b><small>{pendingCount} pending request{pendingCount===1?'':'s'} from patient accounts</small></div><span className="new-order-count">{pendingCount}</span></div>}{error&&<div className="module-error" role="alert"><CircleAlert size={15}/>{error}</div>}{notice&&<div className="module-notice"><Check size={15}/>{notice}</div>}
   {loading?<div className="market-empty">Loading pharmacy orders…</div>:groups.map(([status,title])=>{const rows=orders.filter(o=>key(o.status)===status);return <section className="inventory-panel order-group" key={status}><div className="inventory-panel-head"><div><span className="tiny-label">{status.replaceAll('_',' ')}</span><h2>{title} <span>{rows.length}</span></h2></div>{status==='PENDING'&&pendingCount>0&&<span className="transfer-live"><i/> Refreshed every 20 seconds</span>}</div>{rows.length?<div className="pharmacy-order-list">{rows.map(order=><article className="pharmacy-order-row" key={order.order_id}><div className="patient-order-icon"><PackageCheck size={18}/></div><div className="pharmacy-order-info"><span className="tiny-label">{order.order_id} · PATIENT #{order.user_id}</span><b>{order.medicine_name}</b><small>{order.quantity} strips · {order.medicine_id} · Batch {order.batch_id}</small><small>Patient: {order.patient_name || `User #${order.user_id}`}</small></div><div className="pharmacy-order-total"><b>{money(order.total_amount)}</b><span className={`order-status status-${status.toLowerCase()}`}><i/>{status.replaceAll('_',' ')}</span></div>{actions(order)}</article>)}</div>:<div className="transfer-empty">No {title.toLowerCase()} currently.</div>}</section>})}
   <div className="module-disclaimer"><ShieldCheck size={14}/> Confirmed and ready requests keep stock reserved. Completion decrements on-hand stock once; cancellation releases the reservation.</div>
 </main></div>
}
