import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, CircleAlert, FileImage, ImagePlus, LoaderCircle, PackagePlus, RefreshCw, ScanLine, ShieldCheck, Sparkles, Upload, X } from 'lucide-react'
import Navbar from '../components/Navbar'
import api from '../services/api'

const EMPTY = { medicineName:'', genericName:'', manufacturer:'', medicineId:'', batch:'', batchNumber:'', manufacturingDate:'', expiryDate:'', gtin:'', storageCondition:'Unknown' }
const MAX = 8 * 1024 * 1024
const imageTypes = ['image/jpeg','image/png','image/webp']
const toFormDate=(value)=>{if(!value)return '';const v=String(value).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;return ''}
function getError(error){return error?.response?.data?.detail||error?.userMessage||'Unable to complete this step. Please try again.'}

export default function Restock(){
 const navigate=useNavigate();const videoRef=useRef(null);const streamRef=useRef(null);const detectorRef=useRef(null);const detectionRef=useRef(false);const barcodeGtinRef=useRef('');const chooseFileRef=useRef(null)
 const [step,setStep]=useState('choose');const [file,setFile]=useState(null);const [preview,setPreview]=useState('');const [fields,setFields]=useState(EMPTY);const [quantity,setQuantity]=useState('');const [price,setPrice]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [cameraError,setCameraError]=useState('');const [existing,setExisting]=useState(null);const [saved,setSaved]=useState(null);const [drag,setDrag]=useState(false)
 const resetCamera=()=>{if(streamRef.current){streamRef.current.getTracks().forEach(t=>t.stop());streamRef.current=null}if(videoRef.current)videoRef.current.srcObject=null;detectorRef.current=null;detectionRef.current=false;barcodeGtinRef.current=''}
 useEffect(()=>()=>{resetCamera();if(preview)URL.revokeObjectURL(preview)},[preview])
 const setImage=(candidate)=>{setError('');if(!candidate)return;if(!imageTypes.includes(candidate.type)){setError('Unsupported file type. Choose a JPG, PNG, or WEBP image.');return}if(candidate.size>MAX){setError('Image is too large. Choose an image smaller than 8 MB.');return}setFile(candidate);setPreview(URL.createObjectURL(candidate));setStep('image')}
 const analyze=async(image=file)=>{if(!image)return;setError('');setBusy(true);try{const form=new FormData();form.append('file',image);const {data}=await api.post('/scanner/analyze-image',form,{headers:{'Content-Type':undefined},timeout:90000});const info=data.data||{};setFields({...EMPTY,medicineName:info.medicineName||'',genericName:info.genericName||'',manufacturer:info.manufacturer||'',medicineId:info.medicineId||'',batchNumber:info.batchNumber||'',manufacturingDate:toFormDate(info.manufacturingDate),expiryDate:toFormDate(info.expiryDate),gtin:info.gtin||barcodeGtinRef.current||'',storageCondition:['Ambient Room Temperature','Cold Chain'].includes(info.storageCondition)?info.storageCondition:'Unknown'});setStep('review')}catch(e){setError(getError(e));setStep('image')}finally{setBusy(false)}}
 const capture=async()=>{const video=videoRef.current;if(!video||!video.videoWidth){setCameraError('Camera is still starting. Please wait a moment and try again.');return}const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',0.92));if(!blob){setCameraError('Unable to capture an image. Upload an image instead.');return}resetCamera();setCameraError('');setImage(new File([blob],`pharmsync-camera-${Date.now()}.jpg`,{type:'image/jpeg'}))}
 const openCamera=async()=>{setError('');setCameraError('');setStep('camera');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unavailable');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}if('BarcodeDetector'in window){try{const supported=await window.BarcodeDetector.getSupportedFormats();const formats=['datamatrix','code_128','ean_13','ean_8','upc_a','upc_e','qr_code'].filter(x=>supported.includes(x));if(formats.length){detectorRef.current=new window.BarcodeDetector({formats});scanBarcode()}}catch{}}}catch{resetCamera();setCameraError('Camera access is unavailable on this device. You can upload a medicine image instead.')}}
 const scanBarcode=async()=>{if(!detectorRef.current||!videoRef.current||detectionRef.current)return;try{const codes=await detectorRef.current.detect(videoRef.current);if(codes.length){detectionRef.current=true;const code=codes[0];const raw=String(code.rawValue||'').trim();const fmt=String(code.format||'').toLowerCase();const gs1=raw.match(/(?:\(01\)|01)(\d{14})/);barcodeGtinRef.current=fmt==='datamatrix'?(gs1?.[1]||''):(fmt.startsWith('ean_')&&/^\d{8,14}$/.test(raw)?raw:'');setCameraError(`Code detected (${code.format}). Capturing label for pharmacist review…`);await capture();return}}catch{}if(streamRef.current)setTimeout(scanBarcode,450)}
 const continueReview=()=>{setError('');if(!fields.medicineName.trim()||!fields.batchNumber.trim()||!fields.expiryDate||!fields.manufacturingDate){setError('Enter the medicine name, batch number, manufacturing date, and expiry date before continuing.');return}if(fields.expiryDate<=fields.manufacturingDate){setError('Expiry date must be after the manufacturing date.');return}setStep('quantity')}
 const restock=async()=>{setError('');const qty=Number(quantity),unit=Number(price);if(!Number.isInteger(qty)||qty<=0){setError('Quantity must be a whole number greater than zero.');return}if(!Number.isFinite(unit)||unit<0){setError('Enter a valid unit purchase price.');return}if(!fields.medicineId.trim()){setError('Enter a medicine ID before adding stock.');return}setBusy(true);try{const params={medicine_id:fields.medicineId.trim(),batch_number:fields.batchNumber.trim()};const {data:check}=await api.get('/inventory/restock-check',{params});if(check.exists){setExisting(check.batch);setStep('existing')}else await saveRestock()}catch(e){setError(getError(e))}finally{setBusy(false)}}
 const saveRestock=async()=>{setError('');setBusy(true);try{const payload={medicine_id:fields.medicineId.trim(),medicine_name:fields.medicineName.trim(),batch:fields.batch.trim()||null,batch_number:fields.batchNumber.trim(),quantity:Number(quantity),unit_price:Number(price),manufacture_date:fields.manufacturingDate,expiry_date:fields.expiryDate,storage_condition:fields.storageCondition,batch_status:'active'};const {data}=await api.post('/inventory/restock',payload);setSaved({batch:data.batch,quantityAdded:data.quantity_added,result:data.result});setExisting(null);setStep('success')}catch(e){setError(getError(e));setStep('quantity')}finally{setBusy(false)}}
 const startAnother=()=>{setFile(null);setPreview('');setFields(EMPTY);setQuantity('');setPrice('');setError('');setExisting(null);setSaved(null);setStep('choose')}
 const chooseAnother=(e)=>setImage(e.target.files?.[0])
 const update=(e)=>setFields({...fields,[e.target.name]:e.target.value})
 const field=(key,label,type='text',placeholder='')=><label key={key}>{label}<input name={key} type={type} value={fields[key]||''} onChange={update} placeholder={placeholder} /></label>
 return <div className="site-shell module-shell"><Navbar/><main className="wrap restock-page"><div className="restock-back"><Link to="/inventory"><ArrowLeft size={15}/> Back to inventory</Link><span className="eyebrow"><span className="demo-dot"/> BATCH-BASED STOCK ENTRY</span></div><header className="restock-heading"><span className="restock-title-icon"><PackagePlus size={20}/></span><h1>Add Medicine Stock</h1><p>Scan or upload a medicine batch label to quickly add inventory.</p></header>
 {step==='choose'&&<><section className="restock-choice-grid" aria-label="Choose a medicine intake method"><article className="restock-choice"><div className="restock-option-top"><span className="restock-choice-icon"><Camera size={21}/></span><span className="tiny-label">OPTION 01</span></div><h2>Scan with Camera</h2><p>Use your device camera to scan a medicine strip or package label.</p><button className="button button-green restock-primary-action" onClick={openCamera}><Camera size={18}/> Open Camera</button><small className="restock-secondary-note">Camera permission is optional.</small></article><article className="restock-choice upload-choice"><div className="restock-option-top"><span className="restock-choice-icon"><ImagePlus size={21}/></span><span className="tiny-label">OPTION 02</span></div><h2>Upload Medicine Image</h2><p>Choose a clear package photo from this computer.</p><div className={`restock-dropzone${drag?' is-dragging':''}`} role="button" tabIndex={0} onClick={()=>chooseFileRef.current?.click()} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseFileRef.current?.click()}}} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDrag(false)}} onDrop={e=>{e.preventDefault();setDrag(false);setImage(e.dataTransfer.files?.[0])}}><input ref={chooseFileRef} className="visually-hidden-file" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" onChange={chooseAnother}/><span className="restock-upload-symbol"><Upload size={19}/></span><b>Drag & drop your image here</b><span className="restock-drop-or">or</span><button type="button" className="button button-outline choose-file-button" onClick={e=>{e.stopPropagation();chooseFileRef.current?.click()}}>Choose File</button><small>JPG, PNG or WEBP <i/> up to 8 MB</small></div></article></section><footer className="restock-intake-notes"><div><span className="restock-note-icon"><ScanLine size={17}/></span><p><b>One package provides batch details.</b><span>Enter the total received quantity later; one batch is saved as one inventory record.</span></p></div><div><span className="restock-note-icon"><ShieldCheck size={17}/></span><p><b>Pharmacy-scoped inventory.</b><span>Stock is saved to your authenticated pharmacy node after pharmacist review.</span></p></div></footer></>}
 {step==='camera'&&<section className="restock-work-card"><div className="restock-card-head"><div><span className="tiny-label">CAMERA SCANNER</span><h2>Position the medicine label</h2></div><button className="icon-button" aria-label="Close camera" onClick={()=>{resetCamera();setStep('choose')}}><X size={17}/></button></div>{cameraError&&<div className="restock-error"><CircleAlert size={16}/>{cameraError}</div>}<div className="camera-frame">{!cameraError&&<video ref={videoRef} playsInline muted/>}<span className="camera-corner top-left"/><span className="camera-corner top-right"/><span className="camera-corner bottom-left"/><span className="camera-corner bottom-right"/>{!cameraError&&<span className="camera-scan-line"/>}{cameraError&&<Camera size={40}/>}</div><div className="restock-actions"><button className="button button-outline" onClick={()=>{resetCamera();document.getElementById('fallback-file').click()}}><Upload size={15}/> Upload Image Instead</button>{!cameraError&&<button className="button button-green" onClick={capture}><ScanLine size={15}/> Capture & Analyze</button>}<input id="fallback-file" hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseAnother}/></div><p className="restock-footnote">When supported, the scanner checks DataMatrix, common barcodes and QR. The captured package image is then analyzed for visible text.</p></section>}
 {step==='image'&&<section className="restock-work-card"><div className="restock-card-head"><div><span className="tiny-label">IMAGE UPLOAD</span><h2>Review your package image</h2></div><button className="icon-button" aria-label="Start over" onClick={startAnother}><X size={17}/></button></div><label className="image-dropzone" onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);setImage(e.dataTransfer.files?.[0])}} data-active={drag}><input type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" onChange={chooseAnother}/>{preview?<img className="medicine-preview" src={preview} alt="Selected medicine package"/>:<span className="drop-content"><FileImage size={34}/><b>Drag & drop an image here</b><span>or <u>choose an image</u></span></span>}</label>{file&&<div className="selected-file"><CheckCircle2 size={15}/><span>{file.name}<small>{(file.size/1024/1024).toFixed(2)} MB</small></span><button onClick={()=>{setPreview('');setFile(null)}} aria-label="Remove image"><X size={15}/></button></div>}<p className="restock-footnote">Upload a clear image showing the medicine name, batch number and expiry date. Images are processed for analysis and not retained.</p>{error&&<div className="restock-error"><CircleAlert size={16}/>{error}</div>}<div className="restock-actions"><button className="button button-outline" onClick={()=>document.getElementById('replace-file').click()}><RefreshCw size={15}/> Choose Another Image<input id="replace-file" hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseAnother}/></button><button className="button button-quiet" onClick={()=>{setFields(EMPTY);setStep('review')}}>Enter Manually</button><button className="button button-green" disabled={!file||busy} onClick={()=>analyze()}>{busy?<><LoaderCircle className="spinner-icon" size={16}/> Analyzing…</>:<><Sparkles size={16}/> Analyze Image</>}</button></div></section>}
 {step==='review'&&<section className="restock-work-card"><div className="restock-card-head"><div><span className="tiny-label">PHARMACIST REVIEW</span><h2>Review Medicine Information</h2></div><span className="review-mark"><ShieldCheck size={15}/> Required before saving</span></div><div className="restock-info"><Sparkles size={16}/><span>AI extracted the following information. Please verify it before adding stock. Unreadable details remain blank for you to enter.</span></div><div className="restock-form-grid">{field('medicineName','Medicine Name')}{field('genericName','Generic Name')}{field('manufacturer','Manufacturer')}{field('medicineId','Medicine ID')}{field('batch','Batch Code (optional)')}{field('batchNumber','Batch Number')}{field('manufacturingDate','Manufacturing Date','date')}{field('expiryDate','Expiry Date','date')}{field('gtin','GTIN') }<label>Storage Condition<select name="storageCondition" value={fields.storageCondition} onChange={update}><option>Ambient Room Temperature</option><option>Cold Chain</option><option>Unknown</option></select><small>Confirm the package storage instructions.</small></label></div>{error&&<div className="restock-error"><CircleAlert size={16}/>{error}</div>}<div className="restock-actions"><button className="button button-outline" onClick={()=>file&&analyze(file)} disabled={busy}><RefreshCw size={15}/> Analyze Again</button><button className="button button-quiet" onClick={()=>setFields({...EMPTY,storageCondition:'Unknown'})}>Enter Manually</button><button className="button button-green" onClick={continueReview}>Confirm & Continue <ArrowRight size={15}/></button></div></section>}
 {step==='quantity'&&<section className="restock-work-card"><div className="restock-card-head"><div><span className="tiny-label">RECEIVING DETAILS</span><h2>Quantity Received</h2></div><span className="step-count">02 / 02</span></div><div className="confirmed-product"><span className="restock-choice-icon"><Check size={18}/></span><span><b>{fields.medicineName}</b><small>Medicine ID {fields.medicineId} · Batch {fields.batchNumber}</small></span><button onClick={()=>setStep('review')}>Edit details</button></div><div className="restock-form-grid quantity-grid"><label>Quantity<input type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="e.g. 40"/><small>Enter the total number of strips/units received for this batch.</small></label><label>Unit Purchase Price (₹)<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="e.g. 45.00"/><small>Enter the purchase cost per unit; this is not extracted by OCR.</small></label></div><div className="restock-explainer"><PackagePlus size={17}/><span>One representative image plus total quantity <b>{quantity||'—'}</b> creates one batch record. You do not need to scan every strip.</span></div>{error&&<div className="restock-error"><CircleAlert size={16}/>{error}</div>}<div className="restock-actions"><button className="button button-outline" onClick={()=>setStep('review')}><ArrowLeft size={15}/> Back to Review</button><button className="button button-green" disabled={busy} onClick={restock}>{busy?<><LoaderCircle className="spinner-icon" size={16}/> Checking batch…</>:<>Check & Add Stock <ArrowRight size={15}/></>}</button></div></section>}
 {step==='existing'&&<section className="restock-work-card"><div className="restock-card-head"><div><span className="tiny-label">SAME PHARMACY · SAME BATCH</span><h2>Existing Batch Found</h2></div><span className="existing-badge"><CircleAlert size={15}/> Review needed</span></div><div className="existing-batch"><span className="restock-choice-icon amber"><PackagePlus size={19}/></span><span><b>{existing?.medicine_name||fields.medicineName}</b><small>Batch: {existing?.batch_number||fields.batchNumber} · Current quantity: {existing?.quantity} · Expiry: {String(existing?.expiry_date||'').slice(0,10)}</small></span></div><p className="existing-question">Add {quantity} new units to the existing batch? Quantity will become <b>{Number(existing?.quantity||0)+Number(quantity||0)}</b>.</p>{error&&<div className="restock-error"><CircleAlert size={16}/>{error}</div>}<div className="restock-actions"><button className="button button-outline" onClick={()=>{setExisting(null);setStep('quantity')}}>Cancel</button><button className="button button-green" disabled={busy} onClick={saveRestock}>{busy?'Adding stock…':'Add to Existing Batch'}</button></div></section>}
 {step==='success'&&<section className="restock-work-card success-card"><span className="success-icon"><CheckCircle2 size={28}/></span><span className="tiny-label">MYSQL INVENTORY UPDATED</span><h2>Stock Added Successfully</h2><p className="success-medicine">{saved?.batch?.medicine_name}</p><div className="success-details"><div><small>Batch</small><b>{saved?.batch?.batch_number}</b></div><div><small>Quantity added</small><b>{saved?.quantityAdded} units</b></div><div><small>Expiry</small><b>{saved?.batch?.expiry_date}</b></div><div><small>Unit price</small><b>₹{Number(saved?.batch?.unit_price_inr||0).toFixed(2)}</b></div><div><small>Total batch stock</small><b>{saved?.batch?.quantity}</b></div></div><p className="success-sync"><CheckCircle2 size={15}/> This batch is available in Inventory and POS.</p><div className="restock-actions centered"><button className="button button-outline" onClick={()=>navigate('/inventory')}>View Inventory</button><button className="button button-green" onClick={startAnother}><PackagePlus size={15}/> Add Another Batch</button></div></section>}
 {step!=='choose'&&<div className="restock-trust"><ShieldCheck size={14}/> Stock is saved to your authenticated pharmacy node. OCR data must be confirmed by a pharmacist.</div>}</main></div>
}
