import { Link } from 'react-router-dom'
import { Activity, ArrowUpRight, HeartHandshake, PackageCheck, ShieldCheck, Stethoscope } from 'lucide-react'
import Navbar from '../components/Navbar'
import { roleLabel, useAuth } from '../context/AuthContext'
const modules={
 clinic_phc:{title:'Clinic Demand Dashboard',icon:Stethoscope,message:'Demand matching will be connected in a later step.',cards:[['Medicine requests','08'],['Nearby offers','14'],['Pending transfers','03'],['Stockout risks','02']]},
 charity_ngo:{title:'Charity Network',icon:HeartHandshake,message:'Charity redistribution will be connected in a later step.',cards:[['Eligible donations','11'],['Pending requests','04'],['Received medicines','28'],['Donation history','16']]},
}
export default function RoleDashboard({role}){const {user}=useAuth();const config=modules[role];const Icon=config.icon;return <div className="site-shell dashboard-shell"><Navbar/><main className="dashboard-page wrap"><div className="dashboard-welcome"><div><span className="eyebrow">{roleLabel[role]?.toUpperCase()} PORTAL</span><h1>{config.title}</h1><p>Welcome, <b>{user?.organizationName}</b></p></div><span className="dashboard-date">PHARMSYNC NETWORK <Activity size={14}/></span></div><div className="dashboard-context"><div className="context-icon"><ShieldCheck size={17}/></div><span><b>Your organization workspace</b><small>Signed in as {user?.fullName}. Tools for your organization will be available in a later development phase.</small></span><span className="context-role">{roleLabel[role]}</span></div><div className="dashboard-metrics">{config.cards.map(([label,value],i)=><article className="dashboard-metric" key={label}><div className="dash-metric-icon"><Icon size={18}/></div><span className="dash-metric-label">{label}</span><b>{value}</b><small>Step 2 demo placeholder</small></article>)}</div><div className="dashboard-coming"><div className="coming-icon"><PackageCheck size={18}/></div><div><span className="tiny-label">NEXT DEVELOPMENT PHASE</span><h2>{config.message}</h2><p>Your PharmSync account and role-based access remain active.</p></div><Link to="/" className="back-link">Overview <ArrowUpRight size={14}/></Link></div></main></div>}
